import "./globals.css";
import type { Metadata } from "next";
import classNames from "classnames";
import { outfit, source_serif } from "./font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className={classNames(outfit.variable, source_serif.variable)}
      lang="en"
    >
      <body className="font-outfit overflow-x-hidden h-full">{children}</body>
    </html>
  );
}
